#ifndef GAMEENUMS_HPP
#define GAMEENUMS_HPP

#include "types.h"

namespace MC3DSPluginFramework {

enum GameModes : u8 {
    Survival,
    Creative,
    Adventure,
    Spectator_S,
    Spectator_C,
};

enum class TargetType : u8 {
    Block  = 0,
    Entity = 1,
    None   = 3,
};

enum Dimensions : u8 {
    OverWorld,
    Nether,
    End,
};

enum class Ability : u32 {
    CanFly        = 0xA33AD4,
    IsInvincible  = 0xA33AE0,
    IsFlying      = 0xA33AE4,
    InfiniteItems = 0xA33AE8,
    Lightning     = 0xA33AEC,
    FlySpeed      = 0xA33AF0,
    WalkSpeed     = 0xA33AF4,
    NoClip        = 0xA33AF8,
};

enum class Status : u32 {
    Health              = 0xA33338,
    FollowRange         = 0xA33340,
    KnockbackResistance = 0xA33348,
    Movement            = 0xA33350,    // Speed
    AtackDamage         = 0xA33358,
    Absorption          = 0xA33360,
    Luck                = 0xA33368,
    FallDamage          = 0xA33370,
    HorseJumpStrength   = 0xA33378,
    Hunger              = 0xA33B5C,
    Saturation          = 0xA33B64,
    Exhaustion          = 0xA33B6C,    // 空腹ゲージが減るまでの時間
    Level               = 0xA33B74,
    XP                  = 0xA33B7C,
};

enum class Effects : u32 {
    Speed           = 0xA33560,    // 1
    Slowness        = 0xA33564,    // 2
    Haste           = 0xA33568,    // 3
    Mining_Fatigue  = 0xA3356C,    // 4
    Strength        = 0xA33570,    // 5
    Instant_Health  = 0xA33574,    // 6
    Instant_Damage  = 0xA33578,    // 7
    Jump_boost      = 0xA3357C,    // 8
    Nausea          = 0xA33580,    // 9
    Regeneration    = 0xA33584,    // 10
    Resistance      = 0xA33588,    // 11
    Fire_Resistance = 0xA3358C,    // 12
    Water_Breathing = 0xA33590,    // 13
    Invisibility    = 0xA33594,    // 14
    Blindness       = 0xA33598,    // 15
    Night_Vision    = 0xA3359C,    // 16
    Hunger          = 0xA335A0,    // 17
    Weakness        = 0xA335A4,    // 18
    Poison          = 0xA335A8,    // 19
    Wither          = 0xA335AC,    // 20
    Health_Boost    = 0xA335B0,    // 21
    Absorption      = 0xA335B4,    // 22
    Saturation      = 0xA335B8,    // 23
    Levitation      = 0xA335BC,    // 24
};

enum class ActionFlags : u32 {
    None      = 0,
    Burning   = 1 << 0,     // 0x1, 燃えている
    Sneak     = 1 << 1,     // 0x2, スニーク
    Sprint    = 1 << 3,     // 0x8, ダッシュ
    Eating    = 1 << 4,     // 0x10, 食べる
    Invisible = 1 << 5,     // 0x20, 透明化
    ElytraFly = 1 << 30,    // 0x40000000, エリトラ飛行中
};

enum class EntityVtable : u32 {
    CaveSpider           = 0x9952CC,
    EnderEye             = 0x996078,
    Item                 = 0x996C54,
    SilverFish           = 0x997CCC,
    Wither               = 0x998E98,
    EnderDragon          = 0x99A8C4,
    FishingHook          = 0x99B120,
    Player               = 0x99C31C,
    TNT_Trolley          = 0x99C9B8,
    Mooshroom            = 0x99CF50,
    WitherHead           = 0x99F0A8,
    EndCrystal           = 0x9A002C,
    FallingBlock         = 0x9A0424,
    Potion               = 0x9A2A80,
    XpOrb                = 0x9A48F4,
    FireCharge           = 0x9A5684,
    Thunder              = 0x9A5D98,
    Chest_Trolley        = 0x9A62FC,
    ShulkerBullet        = 0x9A77C0,
    FireCharge_Mini      = 0x9A7B60,
    DragonBreathBullet   = 0x9A97EC,
    Hopper_Trolley       = 0x9AB598,
    Zombie_Villager      = 0x9ADDD4,
    Unknown1             = 0x9AE50C,
    Evoker               = 0x9B2C4C,
    XpBottle             = 0x9B30D4,
    Trolley              = 0x9B3C4C,
    Enderpearl           = 0x9B5D3C,
    Vindicator           = 0x9BAE74,
    Lead                 = 0x9BE774,
    CommandBlock_Trolley = 0x9BECD8,
    Bat                  = 0x9C651C,
    Cow                  = 0x9C69A0,
    Pig                  = 0x9C72A8,
    Vex                  = 0x9C7768,
    Boat                 = 0x9C7C30,
    Wolf                 = 0x9C80DC,
    Arrow                = 0x9C8560,
    Blaze                = 0x9C88C4,
    Ghast                = 0x9C8F2C,
    Horse                = 0x9C93B0,
    Llama                = 0x9C9A5C,
    Sheep                = 0x9C9F2C,
    Slime                = 0x9CA3B0,
    Squid                = 0x9CA85C,
    Witch                = 0x9CAD00,
    Unknown2             = 0x9CB70C,
    Cat                  = 0x9CBA2C,
    Rabbit               = 0x9CC538,
    Spider               = 0x9CCCB0,
    Zombie               = 0x9CD140,
    Chicken              = 0x9CD860,
    Creeper              = 0x9CDCF4,
    Shulker              = 0x9CEC14,
    Enderman             = 0x9CFC9C,
    Guardian             = 0x9D04F8,
    Skeleton             = 0x9D19B4,
    Snowball             = 0x9D1E8C,
    Villager             = 0x9D241C,
    EnderMite            = 0x9D3D94,
    Golem                = 0x9D49C4,
    MagmaCube            = 0x9D4E78,
    LlamaBreath          = 0x9D5558,
    Pigman               = 0x9D5AEC,
    PolarBear            = 0x9D5F74,
    TNT                  = 0x9D63F8,
    SnowGolem            = 0x9D7418,
    Egg                  = 0x9D8030,
};

enum class EntityID {
    Chicken                = 0x130A,
    Cow                    = 0x130B,
    Pig                    = 0x130C,
    Sheep                  = 0x130D,
    Wolf                   = 0x530E,
    Villager               = 0x30F,
    Mooshroom              = 0x1310,
    Squid                  = 0x2311,
    Rabbit                 = 0x1312,
    Bat                    = 0x8113,
    Iron_Golem             = 0x314,
    Snow_Golem             = 0x315,
    Ocelot                 = 0x5316,
    Horse                  = 0x205317,
    Llama                  = 0x131D,
    PolarBear              = 0x131C,
    Donkey                 = 0x205318,
    Mule                   = 0x205319,
    Skelton_Horse          = 0x215B1A,
    Zombie_Horse           = 0x215B1B,
    Zombie                 = 0x30B20,
    Creeper                = 0xB21,
    Skelton                = 0x110B22,
    Spider                 = 0x40B23,
    Zombie_Pigman          = 0x10B24,
    Slime                  = 0xB25,
    EnderMan               = 0xB26,
    SilverFish             = 0x40B27,
    CaveSpider             = 0x40B28,
    Ghast                  = 0xB29,
    MagmaCube              = 0xB2A,
    Blaze                  = 0xB2B,
    Zombie_Villager        = 0x30B2C,
    Witch                  = 0xB2D,
    Stray                  = 0x110B2E,
    Husk                   = 0x30B2F,
    Wither_Skelton         = 0x110B30,
    Guardian               = 0xB31,
    Elder_Guardian         = 0xB32,
    Vindicator             = 0xB39,
    Wither                 = 0x10B34,
    Ender_Dragon           = 0xB35,
    Shulker                = 0xB36,
    Ender_Mite             = 0x40B37,
    Player                 = 0x13F,
    Item                   = 0x40,
    TNT                    = 0x41,
    UNK1                   = 0x42,
    XPbottle               = 0x400044,
    XPOrb                  = 0x45,
    EyeOfEnder             = 0x46,
    EnderCrystal           = 0x47,
    ShulkerBullet          = 0x40004C,
    UNK2                   = 0x4D,
    DragonBreath           = 0x40004F,
    Arrow                  = 0x400050,
    SnowBall               = 0x400051,
    Egg                    = 0x400052,
    UNK3                   = 0x400053,
    Minecart               = 0x80054,
    FireCharge             = 0x400055,
    Potion                 = 0x400056,
    Enderpearl             = 0x400057,
    Lead                   = 0x400058,
    WitherHead             = 0x400059,
    Boat                   = 0x5A,
    WitherHead_Blue        = 0x5B,
    Thunder                = 0x5D,
    Blaze_Bullet           = 0x40005E,
    UNK4                   = 0x5F,
    Hopper_Minecart        = 0x80060,
    TNT_Minecart           = 0x80061,
    Chest_Minecart         = 0x80062,
    Command_Block_Minecart = 0x80064,
    Potion2                = 0x400065,
    LlamaBreath            = 0x400066,
    UNK5                   = 0x400067,
    Evocation_Illager      = 0xB68,
    Vex                    = 0xB69,
};

enum class Enchants {
    Protection,
    Fire_Protection,
    Feather_Falling,
    Blast_Protection,
    Projectile_Protection,
    Thorns,
    Respiration,
    Depth_Strider,
    Aqua_Affinity,
    Sharpness,
    Smite,
    Bane_of_Afthropods,
    Knockback,
    Fire_Aspect,
    Looting,
    Efficiency,
    Silk_Touch,
    Unbreaking,
    Fortune,
    Power,
    Punch,
    Flame,
    Infinity,
    Luck_of_the_Sea,
    Lure,
    Frost_Walker,
    Mending,
};

enum class ParticleID {
    bubble                              = 1,    // 色付け可能
    basic_crit_particle                 = 2,
    black_block                         = 3,    // 雲？
    basic_smoke_particle1               = 4,
    elephant_tooth_paste_vapor_particle = 5,
    misc_fire_vapor_particle            = 6,
    basic_flame_particle                = 7,
    lava_particle                       = 8,
    basic_smoke_particle2               = 9,
    redstone_ore_dust_particle          = 0xA,
    falling_border_dust_particle        = 0xB,
    egg                                 = 0xC,
    snowball                            = 0xD,
    large_explosion                     = 0xE,
    huge_explosion_emitter              = 0xF,
    mobflame_single                     = 0x10,
    heart_particle                      = 0x11,
    block_fragment                      = 0x12,
    Water                               = 0x13,
    basic_portal_particle               = 0x14,
    water_splash_particle               = 0x15,
    water_splash_particle_manual        = 0x16,
    water_wake_particle                 = 0x17,
    lava_drip_particle                  = 0x18,
    falling_dust                        = 0x19,    // 色付け可能
    arrow_spell_emitter                 = 0x1A,    // 色付け可能
    mobspell_emitter                    = 0x1B,    // 色付け可能
    rising_border_dust_particle         = 0x1C,    // 色付け可能
    falling_dust_black                  = 0x1D,
    oozing_ambient                      = 0x1E,
    // water_splash_particle_manual        = 0x1F,
    villager_angry                    = 0x20,
    villager_happy                    = 0x21,
    lab_table_misc_mystical_particle  = 0x22,
    note_particle                     = 0x24,
    infested_emitter                  = 0x25,    // ウィッチが出すモヤモヤ？
    carrot                            = 0x26,
    endrod                            = 0x28,
    eyeofender_death_explode_particle = 0x29,
    explosion_particle                = 0x2A,
    totem_manual                      = 0x2B,
};

enum class EntityActionSet {
    BlockBreaking    = 0x7D1,    // ブロック破壊パーティクル
    Potion           = 0x7D2,    // ポーションが割れる
    DeathDust1       = 0x7D3,
    DeathDust2       = 0x7D4,
    Guardian         = 0x7D6,    // ガーディアンの呪いモーション
    EnderDust1       = 0x7DA,
    EnderDust2       = 0x7DD,
    Dust             = 0x7DF,
    Door             = 0x3EB,
    Ignition         = 0x3ED,
    Anvil            = 0x3FE,
    Drop             = 0x406,    // ドロップ音
    EndermanTeleport = 0x407,    // テレポート音
    PickXP           = 0x41B,
    Lever            = 0xDAC,    // data = 258 or 1F4
};

enum class ItemID : u16 {
    stone                         = 1,
    grass                         = 2,
    dirt                          = 3,
    cobblestone                   = 4,
    planks                        = 5,
    sapling                       = 6,
    bedrock                       = 7,
    flowing_water                 = 8,
    water                         = 9,
    flowing_lava                  = 10,
    lava                          = 11,
    sand                          = 12,
    gravel                        = 13,
    gold_ore                      = 14,
    iron_ore                      = 15,
    coal_ore                      = 16,
    log                           = 17,
    leaves                        = 18,
    sponge                        = 19,
    glass                         = 20,
    lapis_ore                     = 21,
    lapis_block                   = 22,
    dispenser                     = 23,
    sandstone                     = 24,
    noteblock                     = 25,
    tile_bed                      = 26,
    golden_rail                   = 27,
    detector_rail                 = 28,
    sticky_piston                 = 29,
    web                           = 30,
    tallgrass                     = 31,
    deadbush                      = 32,
    piston                        = 33,
    pistonArmCollision            = 34,
    wool                          = 35,
    tile_36                       = 36,
    yellow_flower                 = 37,
    red_flower                    = 38,
    brown_mushroom                = 39,
    red_mushroom                  = 40,
    gold_block                    = 41,
    iron_block                    = 42,
    tile_double_stone_slab        = 43,
    double_stone_slab             = 44,
    brick_block                   = 45,
    tnt                           = 46,
    bookshelf                     = 47,
    mossy_cobblestone             = 48,
    obsidian                      = 49,
    torch                         = 50,
    fire                          = 51,
    mob_spawner                   = 52,
    oak_stairs                    = 53,
    chest                         = 54,
    redstone_wire                 = 55,
    diamond_ore                   = 56,
    diamond_block                 = 57,
    crafting_table                = 58,
    tile_wheat                    = 59,
    farmland                      = 60,
    furnace                       = 61,
    lit_furnace                   = 62,
    standing_sign                 = 63,
    tile_wooden_door              = 64,
    ladder                        = 65,
    rail                          = 66,
    stone_stairs                  = 67,
    wall_sign                     = 68,
    lever                         = 69,
    stone_pressure_plate          = 70,
    tile_iron_door                = 71,
    wooden_pressure_plate         = 72,
    redstone_ore                  = 73,
    lit_redstone_ore              = 74,
    unlit_redstone_torch          = 75,
    redstone_torch                = 76,
    stone_button                  = 77,
    snow_layer                    = 78,
    ice                           = 79,
    snow                          = 80,
    cactus                        = 81,
    clay                          = 82,
    tile_reeds                    = 83,
    tile_84                       = 84,
    fence                         = 85,
    pumpkin                       = 86,
    netherrack                    = 87,
    soul_sand                     = 88,
    glowstone                     = 89,
    portal                        = 90,
    lit_pumpkin                   = 91,
    tile_cake                     = 92,
    unpowered_repeater            = 93,
    powered_repeater              = 94,
    invisibleBedrock              = 95,
    trapdoor                      = 96,
    monster_egg                   = 97,
    stonebrick                    = 98,
    brown_mushroom_block          = 99,
    red_mushroom_block            = 100,
    iron_bars                     = 101,
    glass_pane                    = 102,
    melon_block                   = 103,
    pumpkin_stem                  = 104,
    melon_stem                    = 105,
    vine                          = 106,
    fence_gate                    = 107,
    brick_stairs                  = 108,
    stone_block_stairs            = 109,
    mycelium                      = 110,
    waterlily                     = 111,
    nether_brick                  = 112,
    nether_brick_fence            = 113,
    nether_brick_stairs           = 114,
    tile_nether_wart              = 115,
    enchanting_table              = 116,
    brewingStandBlock             = 117,
    tile_cauldron                 = 118,
    end_portal                    = 119,
    portal_frame                  = 120,
    end_stone                     = 121,
    dragon_egg                    = 122,
    redstone_lamp                 = 123,
    lit_redstone_lamp             = 124,
    dropper                       = 125,
    activator_rail                = 126,
    cocoa                         = 127,
    sandstone_stairs              = 128,
    emerald_ore                   = 129,
    ender_chest                   = 130,
    tripwire_hook                 = 131,
    tripWire                      = 132,
    emerald_block                 = 133,
    spruce_stairs                 = 134,
    birch_stairs                  = 135,
    jungle_stairs                 = 136,
    command_block                 = 137,
    beacon                        = 138,
    cobblestone_wall              = 139,
    tile_flower_pot               = 140,
    carrots                       = 141,
    potatoes                      = 142,
    wooden_button                 = 143,
    tile_skull                    = 144,
    anvil                         = 145,
    trapped_chest                 = 146,
    light_weighted_pressure_plate = 147,
    heavy_weighted_pressure_plate = 148,
    unpowered_comparator          = 149,
    powered_comparator            = 150,
    daylight_detector             = 151,
    redstone_block                = 152,
    quartz_ore                    = 153,
    tile_hopper                   = 154,
    quartz_block                  = 155,
    quartz_stairs                 = 156,
    double_wooden_slab            = 157,
    wooden_slab                   = 158,
    stained_hardened_clay         = 159,
    stained_glass_pane            = 160,
    leaves2                       = 161,
    log2                          = 162,
    acacia_stairs                 = 163,
    dark_oak_stairs               = 164,
    slime                         = 165,
    tile_166                      = 166,
    iron_trapdoor                 = 167,
    prismarine                    = 168,
    seaLantern                    = 169,
    hay_block                     = 170,
    carpet                        = 171,
    hardened_clay                 = 172,
    coal_block                    = 173,
    packed_ice                    = 174,
    double_plant                  = 175,
    tile_176                      = 176,
    tile_177                      = 177,
    daylight_detector_inverted    = 178,
    red_sandstone                 = 179,
    red_sandstone_stairs          = 180,
    tile_double_stone_slab2       = 181,
    double_stone_slab2            = 182,
    spruce_fence_gate             = 183,
    birch_fence_gate              = 184,
    jungle_fence_gate             = 185,
    dark_oak_fence_gate           = 186,
    acacia_fence_gate             = 187,
    repeating_command_block       = 188,
    chain_command_block           = 189,
    tile_190                      = 190,
    tile_191                      = 191,
    tile_192                      = 192,
    tile_spruce_door              = 193,
    tile_birch_door               = 194,
    tile_jungle_door              = 195,
    tile_acacia_door              = 196,
    tile_dark_oak_door            = 197,
    grass_path                    = 198,
    tile_frame                    = 199,
    chorus_flower                 = 200,
    purpur_block                  = 201,
    tile_202                      = 202,
    purpur_stairs                 = 203,
    tile_204                      = 204,
    tile_205                      = 205,
    end_bricks                    = 206,
    frosted_ice                   = 207,
    end_rod                       = 208,
    end_gateway                   = 209,
    tile_210                      = 210,
    tile_211                      = 211,
    tile_212                      = 212,
    magma                         = 213,
    nether_wart_block             = 214,
    red_nether_brick              = 215,
    bone_block                    = 216,
    tile_217                      = 217,
    shulker_box                   = 218,
    glazedTerracotta_purple       = 219,
    glazedTerracotta_white        = 220,
    glazedTerracotta_orange       = 221,
    glazedTerracotta_magenta      = 222,
    glazedTerracotta_light_blue   = 223,
    glazedTerracotta_yellow       = 224,
    glazedTerracotta_lime         = 225,
    glazedTerracotta_pink         = 226,
    glazedTerracotta_gray         = 227,
    glazedTerracotta_silver       = 228,
    glazedTerracotta_cyan         = 229,
    tile_230                      = 230,
    glazedTerracotta_blue         = 231,
    glazedTerracotta_brown        = 232,
    glazedTerracotta_green        = 233,
    glazedTerracotta_red          = 234,
    glazedTerracotta_black        = 235,
    concrete                      = 236,
    concrete_powder               = 237,
    tile_238                      = 238,
    tile_239                      = 239,
    chorus_plant                  = 240,
    stained_glass                 = 241,
    tile_242                      = 242,
    podzol                        = 243,
    tile_beetroot                 = 244,
    stonecutter                   = 245,
    glowingobsidian               = 246,
    netherreactor                 = 247,
    info_update                   = 248,
    info_update2                  = 249,
    movingBlock                   = 250,
    observer                      = 251,
    structure_block               = 252,
    tile_253                      = 253,
    tile_254                      = 254,
    reserved6                     = 255,
    iron_shovel                   = 256,
    iron_pickaxe                  = 257,
    iron_axe                      = 258,
    flint_and_steel               = 259,
    apple                         = 260,
    bow                           = 261,
    arrow                         = 262,
    coal                          = 263,
    diamond                       = 264,
    iron_ingot                    = 265,
    gold_ingot                    = 266,
    iron_sword                    = 267,
    wooden_sword                  = 268,
    wooden_shovel                 = 269,
    wooden_pickaxe                = 270,
    wooden_axe                    = 271,
    stone_sword                   = 272,
    stone_shovel                  = 273,
    stone_pickaxe                 = 274,
    stone_axe                     = 275,
    diamond_sword                 = 276,
    diamond_shovel                = 277,
    diamond_pickaxe               = 278,
    diamond_axe                   = 279,
    stick                         = 280,
    bowl                          = 281,
    mushroom_stew                 = 282,
    golden_sword                  = 283,
    golden_shovel                 = 284,
    golden_pickaxe                = 285,
    golden_axe                    = 286,
    string                        = 287,
    feather                       = 288,
    gunpowder                     = 289,
    wooden_hoe                    = 290,
    stone_hoe                     = 291,
    iron_hoe                      = 292,
    diamond_hoe                   = 293,
    golden_hoe                    = 294,
    wheat_seeds                   = 295,
    wheat                         = 296,
    bread                         = 297,
    leather_helmet                = 298,
    leather_chestplate            = 299,
    leather_leggings              = 300,
    leather_boots                 = 301,
    chainmail_helmet              = 302,
    chainmail_chestplate          = 303,
    chainmail_leggings            = 304,
    chainmail_boots               = 305,
    iron_helmet                   = 306,
    iron_chestplate               = 307,
    iron_leggings                 = 308,
    iron_boots                    = 309,
    diamond_helmet                = 310,
    diamond_chestplate            = 311,
    diamond_leggings              = 312,
    diamond_boots                 = 313,
    golden_helmet                 = 314,
    golden_chestplate             = 315,
    golden_leggings               = 316,
    golden_boots                  = 317,
    flint                         = 318,
    porkchop                      = 319,
    cooked_porkchop               = 320,
    painting                      = 321,
    golden_apple                  = 322,
    sign                          = 323,
    wooden_door                   = 324,
    bucket                        = 325,
    minecart                      = 328,
    saddle                        = 329,
    iron_door                     = 330,
    redstone                      = 331,
    snowball                      = 332,
    boat                          = 333,
    leather                       = 334,
    brick                         = 336,
    clay_ball                     = 337,
    reeds                         = 338,
    paper                         = 339,
    book                          = 340,
    slime_ball                    = 341,
    chest_minecart                = 342,
    egg                           = 344,
    compass                       = 345,
    fishing_rod                   = 346,
    clock                         = 347,
    glowstone_dust                = 348,
    fish                          = 349,
    cooked_fish                   = 350,
    dye                           = 351,
    bone                          = 352,
    sugar                         = 353,
    cake                          = 354,
    bed                           = 355,
    repeater                      = 356,
    cookie                        = 357,
    map                           = 358,
    shears                        = 359,
    melon                         = 360,
    pumpkin_seeds                 = 361,
    melon_seeds                   = 362,
    beef                          = 363,
    cooked_beef                   = 364,
    chicken                       = 365,
    cooked_chicken                = 366,
    rotten_flesh                  = 367,
    ender_pearl                   = 368,
    blaze_rod                     = 369,
    ghast_tear                    = 370,
    gold_nugget                   = 371,
    nether_wart                   = 372,
    potion                        = 373,
    glass_bottle                  = 374,
    spider_eye                    = 375,
    fermented_spider_eye          = 376,
    blaze_powder                  = 377,
    magma_cream                   = 378,
    brewing_stand                 = 379,
    cauldron                      = 380,
    ender_eye                     = 381,
    speckled_melon                = 382,
    spawn_egg                     = 383,
    experience_bottle             = 384,
    fireball                      = 385,
    emerald                       = 388,
    frame                         = 389,
    flower_pot                    = 390,
    carrot                        = 391,
    potato                        = 392,
    baked_potato                  = 393,
    poisonous_potato              = 394,
    emptyMap                      = 395,
    golden_carrot                 = 396,
    skull                         = 397,
    carrotOnAStick                = 398,
    netherStar                    = 399,
    pumpkin_pie                   = 400,
    enchanted_book                = 403,
    comparator                    = 404,
    netherbrick                   = 405,
    quartz                        = 406,
    tnt_minecart                  = 407,
    hopper_minecart               = 408,
    prismarine_shard              = 409,
    hopper                        = 410,
    rabbit                        = 411,
    cooked_rabbit                 = 412,
    rabbit_stew                   = 413,
    rabbit_foot                   = 414,
    rabbit_hide                   = 415,
    horsearmorleather             = 416,
    horsearmoriron                = 417,
    horsearmorgold                = 418,
    horsearmordiamond             = 419,
    lead                          = 420,
    nameTag                       = 421,
    prismarine_crystals           = 422,
    muttonRaw                     = 423,
    muttonCooked                  = 424,
    end_crystal                   = 426,
    spruce_door                   = 427,
    birch_door                    = 428,
    jungle_door                   = 429,
    acacia_door                   = 430,
    dark_oak_door                 = 431,
    chorus_fruit                  = 432,
    chorus_fruit_popped           = 433,
    dragon_breath                 = 437,
    splash_potion                 = 438,
    lingering_potion              = 441,
    command_block_minecart        = 443,
    elytra                        = 444,
    shulker_shell                 = 445,
    totem                         = 450,
    iron_nugget                   = 452,
    beetroot                      = 457,
    beetroot_seeds                = 458,
    beetroot_soup                 = 459,
    salmon                        = 460,
    clownfish                     = 461,
    pufferfish                    = 462,
    cooked_salmon                 = 463,
    appleEnchanted                = 466,
};

enum class gKey : u32 {
    A         = 0,
    B         = 1,
    X         = 2,
    Y         = 3,
    DPadUp    = 4,
    DPadDown  = 5,
    DPadLeft  = 6,
    DPadRight = 7,
    Select    = 8,
    ZL        = 10,    // 0xA
    ZR        = 11,    // 0xB
    Start     = 13,    // 0xD
    L         = 98,    // 0x62
    R         = 99,    // 0x63
};

// A3472C~ BlockTileData

}    // namespace MC3DSPluginFramework

#endif